name: 'Registration field storage'
description: 'Installs field storage for registration fields used by Events and Rides.'
type: 'Field storage'
install:
  - link
  - node
  - options
  - user
# Contrib  
  - honeypot
  - webform
  - webform_civicrm
  - webform_options_limit
  - webform_templates
  - webform_ui
