name: 'Registration field storage'
description: 'Install field storage used by Events and Rides for registration fields.'
type: 'Field storage'
install:
  - link
  - node
  - options
  - user
# Contrib  
  - honeypot
  - webform
  - webform_civicrm
  - webform_options_limit
  - webform_templates
  - webform_ui
config:
  import:
    webform: '*'
    webform_templates:
      - webform.webform.template_contact
      - webform.webform.template_feedback
      - webform.webform.template_issue
      - webform.webform.template_registration
      - webform.webform.template_session_evaluation
      - webform.webform.template_subscribe
      - webform.webform.template_user_profile